version: '3.8'
services:
  pyexam:
    container_name: ExamPython
    image: exam-python:${CODE_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - account_db

  account_db:
    image: postgres
    volumes:
      - ${DB_VOLUME_PATH}/postgres/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
