# Generated by Django 4.0.3 on 2022-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
