# Generated by Django 4.0.3 on 2022-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_localuser_email_confirmed_alter_localuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='username'),
        ),
    ]
