# Generated by Django 4.0.3 on 2022-03-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_localuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='localuser',
            managers=[
            ],
        ),
    ]
